### ISSUE TITLE
글로벌 서버 적용건

### ISSUE THREAD

**Issue by Elysia-ff** [SiGae/FFcord#2]
명령어 인자로 서버 지역도 받게 하면 글로벌서버도 대응할 수 있을 것 같아요.

![image](https://user-images.githubusercontent.com/45890606/88649031-82092a80-d102-11ea-885e-896723cd1220.png)

**Comment by SiGae** [comment]
글로벌서버는 적용 계획이 없습니다. 죄송합니다
